In [1]:
import numpy as np

In [2]:
array = np.array([1,2,3,4,5,6])
array

array([1, 2, 3, 4, 5, 6])

In [3]:
arrays_divididos = np.split(array,3)
arrays_divididos

[array([1, 2]), array([3, 4]), array([5, 6])]

In [4]:
for  i, value in enumerate(arrays_divididos):
    print(f'Parte {i+1} -> {value}')

Parte 1 -> [1 2]
Parte 2 -> [3 4]
Parte 3 -> [5 6]


In [6]:
# Criando um array 1D com temperaturas diárias de um mês (30) dias
temperaturas = np.random.randint(20,40,30)
temperaturas

array([28, 24, 33, 31, 23, 32, 23, 39, 28, 38, 29, 28, 24, 20, 22, 38, 27,
       37, 36, 26, 39, 23, 21, 38, 33, 22, 35, 24, 34, 22], dtype=int32)

In [11]:
# Dividindo as temperaturas em 3 semanas
semanas = np.split(temperaturas, 3)
semanas

[array([28, 24, 33, 31, 23, 32, 23, 39, 28, 38], dtype=int32),
 array([29, 28, 24, 20, 22, 38, 27, 37, 36, 26], dtype=int32),
 array([39, 23, 21, 38, 33, 22, 35, 24, 34, 22], dtype=int32)]

In [12]:
for i, value in enumerate(semanas):
    print(f'Semana {i+1} -> {value}')

Semana 1 -> [28 24 33 31 23 32 23 39 28 38]
Semana 2 -> [29 28 24 20 22 38 27 37 36 26]
Semana 3 -> [39 23 21 38 33 22 35 24 34 22]


In [ ]:
media_semanas = [np.mean(semana) for semana in semanas]


[np.float64(29.9), np.float64(28.7), np.float64(29.1)]

In [16]:
for i, value in enumerate(media_semanas):
    print(f'Média da semana {i+1} -> {value:.2f}°C')

Média da semana 1 -> 29.90°C
Média da semana 2 -> 28.70°C
Média da semana 3 -> 29.10°C
