In [1]:
import numpy as np

In [2]:
array = np.array([10,20,30,40,50])
array

array([10, 20, 30, 40, 50])

In [4]:
# Pesquisar a posição do valor 30
posicao = np.where(array == 30)
posicao

(array([2]),)

In [5]:
# Criar arrau com notas de alunos
notas = np.array([55,67,72,48,90,85,60,50])
notas

array([55, 67, 72, 48, 90, 85, 60, 50])

In [8]:
# pesquisar quais alunos foram aprovados
alunos_aprovados = np.where(notas > 60)
alunos_aprovados

(array([1, 2, 4, 5]),)

In [ ]:
# Buscando as informações das notas
notas[alunos_aprovados]

array([67, 72, 90, 85])

In [10]:
# nota máxima
nota_maxima = np.max(notas)
nota_maxima

np.int64(90)

In [11]:
indice_maximo = np.argmax(notas)
indice_maximo

np.int64(4)