In [2]:
import numpy as np

In [ ]:
array_1d = np.array([1, 2, 3, 4, 5])
print(array_1d.ndim) # número de dimensões
print(array_1d.shape) # formato do array
array_1d

# array de uma única dimensão, muito utilizado em séries temporais ou coleções de valores

1
(5,)


array([1, 2, 3, 4, 5])

In [ ]:
array_2d = np.array([[1,2,3],[4,5,6]])
print(array_2d.ndim) # número de dimensões
print(array_2d.shape) # formato do array
array_2d

# Array de duas dimensões, muito utilizado em matrizes, tabelas de dados e imagens em escala de cinza

2
(2, 3)


array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
array_3d = np.array([[[1,2],[3,4],[5,6],[7,8]]])
print(array_3d.ndim) # número de dimensões
print(array_3d.shape) # formato do array
array_3d

# Pode ser utilizado em imagens em cores (cada matriz representando um canal de cor, como RGB)

3
(1, 4, 2)


array([[[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]])