In [1]:
import numpy as np

In [ ]:
array = np.array([[10,20,30],
                  [40,50,60],
                  [70,80,90]])

print(array.ndim)
print(array.shape)
array

2
(3, 3)


array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [ ]:
# buscalar elemento na linha 1 e coluna 2 [linha, coluna]
print(array[1,2])

60


In [ ]:
# pegar dados da primeira linha [linha, coluna]
print(array[0])

[10 20 30]


In [10]:
# acessando a coluna 1
print(array[:,1])

[20 50 80]


In [ ]:
# fatiamento par obter um subarrey
# linha 0 a 1 (exclusivo) | coluna 1 a 2 (exclusivo)
subarrey = array[0:2, 1:3]
print(subarrey)

[[20 30]
 [50 60]]


In [ ]:
# Criando uma máscara
mascara = array > 50
mascara # forma de filtrar os elementos do array
array[mascara]

array([60, 70, 80, 90])

In [15]:
# modificando elemento na linha 1 e coluna 1

array[1,1] = 105
print(array)

[[ 10  20  30]
 [ 40 105  60]
 [ 70  80  90]]
