# FATIAMENTO

[Linha: coluna(exclusivo)]

In [2]:
import numpy as np

In [3]:
array = np.array([[1,2,3,4,5],
                  [6,7,8,9,10],
                  [11,12,13,14,15],
                  [16,17,18,19,20]])

In [5]:
print(array.ndim)
print(array.shape)

2
(4, 5)


In [8]:
# fatiando as duas primeiras linhas

array[0:2, :]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [9]:
# fatiando as 3 primeiras colunas
array[:, :3]

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])

In [11]:
subarray = array[1:3, 1:3]
subarray

array([[ 7,  8],
       [12, 13]])

In [12]:
subarray_lateral = array[1:3, 3:5]
print(subarray_lateral)

[[ 9 10]
 [14 15]]


In [13]:
# Modificar um subarray
array[1:3, 1:3] = [[99,100], [101,102]]
array

array([[  1,   2,   3,   4,   5],
       [  6,  99, 100,   9,  10],
       [ 11, 101, 102,  14,  15],
       [ 16,  17,  18,  19,  20]])