# Funções



In [1]:
import numpy as np

In [3]:
array = np.array([1,2,3,4,5])
type(array)

numpy.ndarray

In [4]:
# adição
soma = np.add(array, 10)
soma

array([11, 12, 13, 14, 15])

In [5]:
# Subtração
subtracao = np.subtract(array, 5)
subtracao

array([-4, -3, -2, -1,  0])

In [8]:
# multiplicação
produto = np.multiply(array, 2)
produto

array([ 2,  4,  6,  8, 10])

In [10]:
# divisão
divisao = np.divide(array, 2 )
divisao

array([0.5, 1. , 1.5, 2. , 2.5])

In [12]:
# 5- Funções Trigonométricas
seno  = np.sin(array)
seno

cosseno = np.cos(array)
cosseno

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

In [ ]:
# Funções estatísticas
media = np.mean(array)
print(media)

desvio = np.std(array)
print(desvio)

3.0
1.4142135623730951


In [18]:
# Funções de comparação
maior_3 = array > 3
print(maior_3)

maior_4 = np.greater(array,4) # outra forma de fazer a comparação
print(maior_4)

[False False False  True  True]
[False False False False  True]


In [20]:
# Combinando funções
resultado = np.sqrt(array) + np.power(array,2)
resultado

array([ 2.        ,  5.41421356, 10.73205081, 18.        , 27.23606798])

In [21]:
# Funções exponenciais
exponencial = np.exp(array)
exponencial

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [22]:
# Função de logaritmo
logaritimo =np.log(array)
logaritimo

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [26]:
# Função de arredondamento
arredondamento = np.round(array/2,4)
arredondamento

array([0.5, 1. , 1.5, 2. , 2.5])

In [29]:
# Função de potencia
potencia = np.power(array, 5)
potencia

array([   1,   32,  243, 1024, 3125])