Copy
- Uma nova cópia do array é criada em memória, isso significa que as duas matrizes (original e cópia) são independentes uma da outra

View
- Não é criada uma nova cópia na memória.
A viwe compartilha os mesmos dados que o array original

In [2]:
import numpy as np

In [3]:
array_original = np.array([[1,2,3],
                           [4,5,6],
                           [7,8,9]])

array_original

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# cópia rasa (view)
copia_rasa = array_original[1:,1:]
copia_rasa

array([[5, 6],
       [8, 9]])

In [6]:
copia_rasa[0,0] = 99
copia_rasa

array([[99,  6],
       [ 8,  9]])

In [8]:
# A copia rasa alterou o array original
array_original

array([[ 1,  2,  3],
       [ 4, 99,  6],
       [ 7,  8,  9]])

In [10]:
# Cópia profunda

array_copia = array_original.copy()


In [14]:
# A cópia profunda não altera o array original 
array_copia[0,0] = 1000
array_copia

array([[1000,    2,    3],
       [   4,   99,    6],
       [   7,    8,    9]])

In [13]:
array_original

array([[ 1,  2,  3],
       [ 4, 99,  6],
       [ 7,  8,  9]])